"""Curated 2026 issue copy. Facts only; no purchase links."""
from __future__ import annotations

# 8 books per language, first published in 2026 (within last 12 months as of 2026-09-17).
FEATURED = [
    # ---------- English ----------
    {
        "matchTitle": "The Sleeping Sisters",
        "languageCode": "en",
        "chineseTitle": "沉睡的姐妹",
        "publicationDate": "2026-01-01",
        "isbn13": "9780316581554",
        "publisher": "Little, Brown",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "文学小说"],
        "tags": ["文学悬疑", "家庭", "沙漠"],
        "coverImage": "/covers/sleeping-sisters.jpg",
        "editorQuoteZh": "沙漠还没醒，家里的秘密先醒了。",
        "readingMoodZh": "干燥、迟缓、带一点神话余温的文学悬疑。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Little, Brown catalog / ISBN",
        "sourceUrl": "",
        "selectionReason": "2026 年首次出版，且已有可靠 ISBN 与封面。",
        "author": {
            "name": "Jennifer Givhan",
            "localizedName": "詹妮弗·吉凡",
            "nationality": "美国",
            "biographyZh": "Jennifer Givhan 是美国诗人与小说家，长期书写西南部土地、母系记忆与身体经验。她擅长把神话的幽光放进当代家庭，让风景不仅是背景，也成为人物命运的一部分。",
        },
        "fullDescriptionZh": "新墨西哥的沙漠看似沉睡，地下的热与一个家庭压抑多年的秘密却同时升温。有人守着孩子，有人追查一件始终无法真正结束的事，也有人渐渐意识到：这片土地或许比所有人更早知道结局。照料、血缘与怀疑彼此纠缠，平静的日常被一点点烘出裂缝。",
        "recommendationZh": "这本书最迷人的地方，是它不急着吓你。危险藏在热浪、尘土和一家人欲言又止的停顿里，等你察觉时，空气已经变了。它有诗意，但不是为了显得漂亮；那些句子让家庭秘密更沉，也让沙漠真正有了呼吸。",
        "audienceZh": "如果你喜欢文学悬疑、美国西南部的荒凉景色，或者比起“凶手是谁”更在意一家人为什么走到这一步，可以读。只想追密集反转的话，它可能慢了一点。",
    },
    {
        "matchTitle": "God's Country",
        "languageCode": "en",
        "chineseTitle": "上帝的国度",
        "publicationDate": "2026-08-01",
        "isbn13": "9781668231869",
        "publisher": "Atria",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "推理"],
        "tags": ["荒野", "犯罪", "文学悬疑"],
        "coverImage": "/covers/gods-country.jpg",
        "editorQuoteZh": "边界水域里，风景比人更会设局。",
        "readingMoodZh": "冷、湿、辽阔，像把侦探小说拖进没信号的地方。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Atria / ISBN 9781668231869",
        "sourceUrl": "",
        "selectionReason": "2026年8月新作，ISBN 与作者系列信息可核。",
        "author": {
            "name": "William Kent Krueger",
            "localizedName": "威廉·肯特·克鲁格",
            "nationality": "美国",
            "biographyZh": "William Kent Krueger 以 Cork O’Connor 系列闻名，长期书写美国北部森林、湖泊与原住民土地上的案件。他的推理路径清楚，却从不把人的选择写得简单。",
        },
        "fullDescriptionZh": "边界水域出现一具尸体，又有人被挟为人质。调查者必须穿过湖泊、森林和不断变化的天气，在有限时间里判断谁可信、谁正在隐瞒。来到荒野的人都带着旧日亏欠，案件只是撕开它们的第一道口子。",
        "recommendationZh": "这里的荒野一点也不浪漫：水会拖慢搜寻，天气会打乱判断，森林甚至会替人藏住证据。案情当然抓人，但更难忘的是那种无边的寂静——人在其中显得很小，每一个决定却又重得惊人。",
        "audienceZh": "喜欢户外犯罪、警察调查和地方感强烈的小说，可以从这本开始。如果你只爱密室里的心理较量，这片天地或许显得太开阔。",
    },
    {
        "matchTitle": "The Best I Never Had",
        "languageCode": "en",
        "chineseTitle": "我从未真正拥有的最好",
        "publicationDate": "2026-08-01",
        "isbn13": "9781250341587",
        "publisher": "St. Martin's Griffin",
        "primaryGenre": "爱情",
        "genres": ["爱情"],
        "tags": ["假约会", "重逢", "轻松浪漫"],
        "coverImage": "/covers/best-i-never-had.jpg",
        "editorQuoteZh": "假的三年，真的一周，婚礼把旧账摊开。",
        "readingMoodZh": "轻、热、带着一点尴尬的甜。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "St. Martin's Griffin / ISBN",
        "sourceUrl": "",
        "selectionReason": "2026年8月出版的英语浪漫小说，封面资料完整。",
        "author": {
            "name": "Amy Buchanan",
            "localizedName": "艾米·布坎南",
            "nationality": "美国",
            "biographyZh": "Amy Buchanan 擅长以日常场景和快速对话书写亲密关系。她从读者熟悉的浪漫设定出发，真正关心的却是两个人如何停止表演，重新学习坦白。",
        },
        "fullDescriptionZh": "一场婚礼让两个曾以“假情侣”身份互相解围的人，在分开三年后重新见面。筹备、亲友和熟悉的旧地不断唤醒当年的默契，也迫使他们承认：那段表演留下的并不只是笑话，还有一笔从未结清的感情旧账。",
        "recommendationZh": "“假装相爱，结果认真了”并不新鲜，好看的是作者把两个人的嘴硬、自尊和迟到的诚实都写得很真。它甜，却不是糖浆一样的甜；婚礼周越热闹，那些没说出口的话就越明显。",
        "audienceZh": "适合想看重逢、假恋爱成真和婚礼周暧昧的人。想找一段轻松但不空心的爱情故事，它会很合适。",
    },
    {
        "matchTitle": "The Book of Chuck",
        "languageCode": "en",
        "chineseTitle": "查克之书",
        "publicationDate": "2026-01-01",
        "isbn13": "9780593854549",
        "publisher": "Tiny Reparations",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["家族", "南方", "奇幻边缘"],
        "coverImage": "/covers/book-of-chuck.jpg",
        "editorQuoteZh": "有人一碰就能看见死亡，家族却仍要过日子。",
        "readingMoodZh": "沉、热、带一点超自然的家族史诗。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Tiny Reparations / ISBN",
        "sourceUrl": "",
        "selectionReason": "2026年英语文学新作，ISBN 与封面可核。",
        "author": {
            "name": "LaToya Watkins",
            "localizedName": "拉托娅·沃特金斯",
            "nationality": "美国",
            "biographyZh": "LaToya Watkins 关注得州、黑人家庭与代际责任。她笔下的奇异事件从不只是奇观，而是迫使家族重新分配爱、秘密与责任的力量。",
        },
        "fullDescriptionZh": "得州一个家族中，有人只需触碰便会看见不该提前知道的事。这样的能力没有带来荣耀，反而进入母亲、儿子与姐妹的日常，成为无法推卸的负担。家人一边维持生活，一边决定哪些预兆应该说出口、哪些秘密必须以照料的名义继续保存。",
        "recommendationZh": "它没有把预知当成酷炫的礼物，而是写成一种很难与家人解释的负担。真正让人揪心的不是“看见了什么”，而是知道之后还要不要说、还能不能照常去爱。奇异设定落到了生活里，反而更疼。",
        "audienceZh": "喜欢家族群像、南方文学和一点点超自然的人会读得进去。它关心的是人，不是能力说明书，硬科幻读者要先调整期待。",
    },
    {
        "matchTitle": "The Calamities",
        "languageCode": "en",
        "chineseTitle": "灾厄",
        "publicationDate": "2026-08-01",
        "isbn13": "9798217091812",
        "publisher": "Del Rey",
        "primaryGenre": "奇幻",
        "genres": ["奇幻"],
        "tags": ["暗黑奇幻", "家族", "当代"],
        "coverImage": "/covers/calamities.jpg",
        "editorQuoteZh": "这家人做灵魂买卖，账本比血更清楚。",
        "readingMoodZh": "脏金、喧闹、带着诅咒的家族传奇。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Del Rey / ISBN",
        "sourceUrl": "",
        "selectionReason": "2026年8月成人奇幻新作，ISBN 可核。",
        "author": {
            "name": "Chuck Wendig",
            "localizedName": "查克·温迪格",
            "nationality": "美国",
            "biographyZh": "Chuck Wendig 横跨惊悚、奇幻与末日题材，文风快速、密集而带刺。他尤其擅长把民间传说拖进加油站、餐桌和普通家庭，让怪物与日常彼此照面。",
        },
        "fullDescriptionZh": "一个半人半魔的家族靠灵魂交易维持生意。契约有规矩，家族有辈分，而每个人都在试探规则能被破坏到什么程度。当当代生活与古老诅咒叠在一起，“家庭企业”成了最危险也最难退出的职业。",
        "recommendationZh": "把“家族生意”换成灵魂买卖以后，继承、忠诚和离家出走都变得格外要命。书里的人嘴很坏，日子更坏，偏偏总能在最不该笑的时候让人笑出来。它吵闹、粗粝，也很有生命力。",
        "audienceZh": "如果你喜欢暗黑奇幻、黑色幽默和乱成一团的危险家族，这本很对味。怕脏话、怕血腥、想看清淡幻想的人可以绕开。",
    },
    {
        "matchTitle": "Immortal Rose",
        "languageCode": "en",
        "chineseTitle": "不朽玫瑰",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "HarperCollins",
        "primaryGenre": "奇幻",
        "genres": ["奇幻", "爱情"],
        "tags": ["浪漫奇幻", "香水", "代价"],
        "coverImage": "/covers/immortal-rose.jpg",
        "editorQuoteZh": "香味能封住魔法，交易却封不住后果。",
        "readingMoodZh": "香、密、带一点危险的华丽。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "HarperCollins listing; ISBN 待书店页复核",
        "sourceUrl": "",
        "selectionReason": "2026年成人奇幻新作，封面已有；ISBN 在目录中缺失，故标待核验。",
        "author": {
            "name": "Alexandra Bracken",
            "localizedName": "亚历山德拉·布拉肯",
            "nationality": "美国",
            "biographyZh": "Alexandra Bracken 以青年及成人幻想小说知名，善于把能力、契约和情感选择绑在一起。她的世界规则明晰，而人物往往必须为自己最渴望的东西付出代价。",
        },
        "fullDescriptionZh": "在这个世界里，香水封存着魔法，每一种气味都对应一场交易。有人借香气获得渴望之物，也有人发现代价会像气味一样附着在记忆和身体上。故事围绕制作、交换与欲望展开：越是迷人的芬芳，越可能悄悄改写人的判断。",
        "recommendationZh": "许多奇幻小说让你看见魔法，这一本先让你闻到它。香水不是漂亮摆设，而是欲望、交易和控制人的工具。读到后来，你会开始怀疑每一种迷人的气味背后，是不是都藏着一张账单。",
        "audienceZh": "喜欢浪漫奇幻、香水、炼制工艺和“愿望总要付费”这类设定的人，大概率会爱上它。想看千军万马的史诗读者，可能会嫌它太贴近肌肤。",
    },
    {
        "matchTitle": "My Sister Is Going to Kill Me",
        "languageCode": "en",
        "chineseTitle": "我姐姐要杀了我",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "William Morrow",
        "primaryGenre": "推理",
        "genres": ["推理", "家庭"],
        "tags": ["姐妹", "户外", "家庭推理"],
        "coverImage": "/covers/sister-kill.jpg",
        "editorQuoteZh": "漂流可以是度假，也可以是不在场证明。",
        "readingMoodZh": "阳光明亮，水面下发紧。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "William Morrow listing; ISBN 待核",
        "sourceUrl": "",
        "selectionReason": "2026年家庭推理新书，封面已有；ISBN 缺失，标待核验。",
        "author": {
            "name": "Nina Simon",
            "localizedName": "尼娜·西蒙",
            "nationality": "美国",
            "biographyZh": "Nina Simon 擅长观察一群人如何共同经历一件事。她写姐妹关系时，同时保留亲近、竞争、照料和旧伤，使案件始终扎在真实生活之中。",
        },
        "fullDescriptionZh": "一对姐妹参加大峡谷漂流，本想借旅程修补关系。装备分配、划桨节奏和谁来承担风险，很快暴露她们多年的竞争与怨气；命案发生后，“我们是一家人”突然变成需要接受审视的证词。河道的危险清晰可见，熟悉的人心却更难判断。",
        "recommendationZh": "漂流本来就需要把后背交给同行的人，偏偏同行的是最了解你、也最知道怎样伤害你的姐姐。阳光和河水越明亮，姐妹之间的旧账越显得发冷。它让“家人”从安全答案，变成了需要重新审问的问题。",
        "audienceZh": "适合喜欢家庭推理、姐妹关系和户外冒险的人。它更在意关系里的暗流，不是纯粹拿诡计取胜的本格谜题。",
    },
    {
        "matchTitle": "Dear Debbie",
        "languageCode": "en",
        "chineseTitle": "亲爱的黛比",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Poisoned Pen",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "惊悚"],
        "tags": ["复仇", "心理悬疑"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "专栏里的建议，她决定先用在自己身上。",
        "readingMoodZh": "快、利、带着一点痛快的凉。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Poisoned Pen / 2026 fiction lists",
        "sourceUrl": "",
        "selectionReason": "2026年英语畅销向悬疑新书；ISBN 待书店复核。",
        "author": {
            "name": "Freida McFadden",
            "localizedName": "弗蕾达·麦克法登",
            "nationality": "美国",
            "biographyZh": "Freida McFadden 是英语畅销悬疑的重要作者，作品以短章节、强钩子与密集反转见长。她有医学背景，尤其擅长书写封闭空间和表面正常、内部失衡的关系。",
        },
        "fullDescriptionZh": "黛比多年为陌生读者撰写人生建议，自己的生活却突然失去控制。面对崩塌的家庭与积压的愤怒，她开始把曾经写给别人的忠告逐条用于自己。每一次“照做”都带来更难收拾的后果，也让善意建议逐渐显出危险的一面。",
        "recommendationZh": "看一个总替别人解决人生问题的人，把自己的生活越处理越糟，有一种危险的痛快。每条建议听起来都很有道理，真正照做却像多米诺骨牌。它未必让你回味很久，但很可能让你凌晨还在翻页。",
        "audienceZh": "喜欢短章节、心理悬疑、女性复仇和“再读一章就睡”的读者，请小心打开。想慢慢品句子的人，可能会觉得它跑得太快。",
    },
    # ---------- Spanish ----------
    {
        "matchTitle": "Los Huérfanos",
        "languageCode": "es",
        "chineseTitle": "孤儿们",
        "publicationDate": "2026-09-09",
        "isbn13": "",
        "publisher": "Planeta",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "推理"],
        "tags": ["黑手党", "家族", "马贝拉"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "马贝拉的阳光很好，阴影里的家族更好。",
        "readingMoodZh": "热、暴、像犯罪编年史。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Planeta / RTVE 2026-09-09 coverage",
        "sourceUrl": "",
        "selectionReason": "2026年9月9日西班牙原版出版。",
        "author": {
            "name": "Carmen Mola",
            "localizedName": "卡门·莫拉",
            "nationality": "西班牙",
            "biographyZh": "Carmen Mola 是三位作家共用的笔名，以高速、黑暗的犯罪小说闻名。他们尤其擅长书写家庭如何把暴力变成日常秩序。",
        },
        "fullDescriptionZh": "三个从孤儿院一起活下来的人，把马贝拉的犯罪网络变成替代家庭。另一股家族势力与一位拒绝宽恕的姐姐步步逼近，旧忠诚、新利益和血债开始冲突。阳光海岸不再只是度假胜地，而是一张由腐败、资本和暴力绘成的权力地图。",
        "recommendationZh": "这不是一个侦探站在尸体旁寻找答案的故事，而是一群人把犯罪过成日常以后，怎样继续相信“我们是一家人”。人物很多，关系很脏，叙事却始终有速度。马贝拉的海风和阳光越明亮，那些暗处的交易就越刺眼。",
        "audienceZh": "喜欢黑帮家族、犯罪群像和西班牙黑色小说的人会读得很过瘾。书里不回避暴力，也没有多少干净角色，对残酷场面敏感的话要谨慎。",
    },
    {
        "matchTitle": "La piel de una gota",
        "languageCode": "es",
        "chineseTitle": "一滴水的皮肤",
        "publicationDate": "2026-09-16",
        "isbn13": "",
        "publisher": "Destino",
        "primaryGenre": "推理",
        "genres": ["推理", "悬疑"],
        "tags": ["警察程序", "爆炸", "巴利亚多利德"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "城市被点亮的那一刻，有人把它当成靶子。",
        "readingMoodZh": "急促、城市、程序与恐慌并行。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Destino / author site 2026-09-16",
        "sourceUrl": "",
        "selectionReason": "2026年9月16日出版，探长系列回归。",
        "author": {
            "name": "César Pérez Gellida",
            "localizedName": "塞萨尔·佩雷斯·赫伊达",
            "nationality": "西班牙",
            "biographyZh": "César Pérez Gellida 是西班牙黑色小说的重要作者，以巴利亚多利德和探长 Sancho 系列著称。他的故事节奏快，同时保留警察工作的具体细节。",
        },
        "fullDescriptionZh": "巴利亚多利德接连遭遇袭击，节日灯光迅速变成恐慌背景。一名带着军人式纪律的凶手按自己的逻辑行动；探长 Ramiro Sancho 则必须在私人生活与公共危机之间分配注意力，沿广场、街道和警务程序寻找下一步线索。",
        "recommendationZh": "袭击制造紧张，真正把人困住的却是这座城市。你会跟着 Sancho 穿过熟悉的广场、节庆人群和漫长的警务程序，看一个原本可以照常生活的地方怎样一点点失去安全感。它有速度，也有警察小说难得的疲惫感。",
        "audienceZh": "爱看警察怎样一点点排查、也喜欢城市本身参与案件的人，很适合读。若你只想看封闭空间里的心理游戏，这一本的视野会更大、更嘈杂。",
    },
    {
        "matchTitle": "Un hombre de honor",
        "languageCode": "es",
        "chineseTitle": "一个有荣誉的人",
        "publicationDate": "2026-09-30",
        "isbn13": "9788408326595",
        "publisher": "Planeta",
        "primaryGenre": "历史",
        "genres": ["历史", "爱情"],
        "tags": ["纽约", "一九六八", "家族"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "一九六八年的纽约，荣誉是一种昂贵的借口。",
        "readingMoodZh": "宽、热、历史通俗长篇的推进感。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Planeta ISBN 9788408326595",
        "sourceUrl": "",
        "selectionReason": "2026年9月30日出版，ISBN 可核。",
        "author": {
            "name": "Paloma Sánchez-Garnica",
            "localizedName": "帕洛玛·桑切斯-加尔尼卡",
            "nationality": "西班牙",
            "biographyZh": "Paloma Sánchez-Garnica 擅长书写家族秘密、历史记忆与政治压力下的个人选择。她的作品情感明确、结构易读，让更广泛的读者进入复杂时代。",
        },
        "fullDescriptionZh": "1968 年纽约，一名女记者试图在男性主导的新闻界站稳脚跟，一名警察则穿行在哈莱姆、腐败与家族势力之间。越战与民权运动构成时代远景，调查和爱情却在近处互相拖累。“荣誉”既是男人们的口号，也成为每个人必须付出代价的选择。",
        "recommendationZh": "它有老派长篇小说的满足感：时代在外面翻涌，爱情、工作和家族义务在里面彼此拉扯。越战、民权和黑手党的影子没有压扁人物，反而让每个私人选择都显得更昂贵。读它像追一部长而不乱的年代剧。",
        "audienceZh": "喜欢年代剧、家族故事，以及爱情和调查两条线一起走的人，可以安心翻开。偏爱极简小说的读者，可能会觉得它铺得太开。",
    },
    {
        "matchTitle": "Comerás flores",
        "languageCode": "es",
        "chineseTitle": "你将吃花",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Libros del Asteroide",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "文学小说"],
        "tags": ["年龄差", "欲望", "当代西班牙"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "爱情若长在湿处，花也会有味道。",
        "readingMoodZh": "黏、暗、句子漂亮但不安慰人。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Libros del Asteroide / 2026 Spanish lists",
        "sourceUrl": "",
        "selectionReason": "2026年西班牙现象级新作；精确月份与ISBN待核。",
        "author": {
            "name": "Lucía Solla Sobral",
            "localizedName": "露西亚·索亚·索布拉尔",
            "nationality": "西班牙",
            "biographyZh": "Lucía Solla Sobral 是近年受到关注的西班牙新声音。她的文字细密，善于让美感既吸引读者，也同时发出警告。",
        },
        "fullDescriptionZh": "一段年龄悬殊的感情从迷人开始，爱与利用却越来越难分辨。“吃花”这个过分美丽的意象逐渐落到身体、阶层和权力上：谁被欣赏成风景，谁又在关系里拥有真正的选择？危险并非突然降临，而是在亲密中慢慢显形。",
        "recommendationZh": "它写得很美，却不会让美替这段关系开脱。花、身体和被凝视的年轻女性都带着诱惑，读者也会在被吸引的同时逐渐察觉不对。真正的悬念不是谁撒了谎，而是她要到什么时候才能看清自己正被怎样对待。",
        "audienceZh": "如果你关心爱情里的年龄差、阶级和控制，也愿意读一部漂亮却不安慰人的小说，可以选它。想要纯甜恋爱的话，最好不要被书名里的花骗进去。",
    },
    {
        "matchTitle": "Mentira",
        "languageCode": "es",
        "chineseTitle": "谎言",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Ediciones B",
        "primaryGenre": "推理",
        "genres": ["推理", "悬疑"],
        "tags": ["犯罪", "谎言", "畅销"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "标题已经坦白：谎言才是引擎。",
        "readingMoodZh": "快、滑、大众犯罪小说的推进。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Ediciones B / Sant Jordi 2026 lists",
        "sourceUrl": "",
        "selectionReason": "2026年圣乔治日西语热销新作；ISBN待核。",
        "author": {
            "name": "Juan Gómez-Jurado",
            "localizedName": "胡安·戈麦斯-胡拉多",
            "nationality": "西班牙",
            "biographyZh": "Juan Gómez-Jurado 是西班牙当代极具国际影响力的犯罪小说家，叙事清楚、推进迅速，尤其擅长用短场景和强悬念维持阅读惯性。",
        },
        "fullDescriptionZh": "人物用谎言保护自己，也用同一套谎言伤害他人。调查者必须穿过彼此嵌套的假话，找出仍能承受事实的那一条线。网站现有资料未提供足够具体的人物与案情，正式上线前应以出版社梗概补足，避免把类型概述误当情节。",
        "recommendationZh": "戈麦斯-胡拉多很清楚读者会在哪里停下来，于是总在那个位置再推你一把。场景短、转得快，谎言一层套一层，很适合用来找回阅读原版小说的速度。不过现有资料还没说清人物和案件，正式页面最好补上真正能抓住人的故事起点。",
        "audienceZh": "喜欢畅销犯罪小说、短章节和强钩子的人会读得顺，尤其适合戈麦斯-胡拉多的老读者。",
    },
    {
        "matchTitle": "La intriga del funeral inconveniente",
        "languageCode": "es",
        "chineseTitle": "一场不合时宜葬礼的阴谋",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Seix Barral",
        "primaryGenre": "推理",
        "genres": ["推理", "文学小说"],
        "tags": ["讽刺", "葬礼", "幽默"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "葬礼最怕准时，更怕有人认真。",
        "readingMoodZh": "讽、轻、智性的西班牙式玩笑。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Seix Barral / Sant Jordi 2026",
        "sourceUrl": "",
        "selectionReason": "2026年圣乔治日西语小说高销量新作。",
        "author": {
            "name": "Eduardo Mendoza",
            "localizedName": "爱德华多·门多萨",
            "nationality": "西班牙",
            "biographyZh": "Eduardo Mendoza 是西班牙当代文学的重要幽默家，能在严肃历史与侦探闹剧之间自由切换。他笔下的巴塞罗那既庄严，又总有人在制度中出丑。",
        },
        "fullDescriptionZh": "一场来得不合时宜的葬礼，把哀悼者、家族秘密与城市旁观者聚到同一处。礼仪原本用来维持体面，却不断泄露破绽；每一次得体发言都可能掩盖新的谎言。案件在讽刺与误会中推进。",
        "recommendationZh": "葬礼本该让所有人安静守礼，偏偏每个人越想维持体面，就越容易露出破绽。门多萨的好笑不是插科打诨，而是看人怎样被礼仪、身份和自己的谎话绊倒。案子有趣，人情更有趣。",
        "audienceZh": "喜欢轻推理、文学幽默和巴塞罗那城市气息的人会很舒服。想找血腥硬派 noir，就不是这一本。",
    },
    {
        "matchTitle": "La ciudad de las luces muertas",
        "languageCode": "es",
        "chineseTitle": "死灯之城",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Destino",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "历史"],
        "tags": ["纳达尔奖", "城市", "记忆"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "灯灭了，城市才开始被真正看见。",
        "readingMoodZh": "文学、意象浓、奖项向长篇。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Destino / Premio Nadal 2026 reports",
        "sourceUrl": "",
        "selectionReason": "2026纳达尔奖作品，当年出版。",
        "author": {
            "name": "David Uclés",
            "localizedName": "达维德·乌克莱斯",
            "nationality": "西班牙",
            "biographyZh": "David Uclés 因纳达尔奖受到更广泛关注，写作偏向城市记忆与意象组织。作者生平及本书细节仍建议以官方书讯复核。",
        },
        "fullDescriptionZh": "一座城市的灯光、熄灭与记忆被写成可以行走的空间。公共历史与私人观看彼此重叠，“灯”既是城市设施，也是辨认过去的隐喻。网站资料尚缺具体人物和事件，正式页面应在出版社信息核实后补充主角与核心行动线。",
        "recommendationZh": "这本书显然不想靠连续反转抓人，它更在意一座城市熄灯以后，哪些记忆反而开始发亮。意象和句子会比事件走得更远。可惜现有资料还不够具体，正式上线前一定要补齐主角和故事起点，否则再美的形容也只是雾。",
        "audienceZh": "喜欢城市记忆、象征性叙事和文学奖作品的人可以留意。若阅读时一定要有清楚、快速的情节线，可能会觉得它太慢。",
    },
    {
        "matchTitle": "Han cantado bingo",
        "languageCode": "es",
        "chineseTitle": "他们唱了宾果",
        "publicationDate": "2026-05-01",
        "isbn13": "",
        "publisher": "Reservoir Books",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "成长"],
        "tags": ["岛屿", "姐妹", "兰萨罗特"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "宾果唱响之前，两姐妹已经把火山当成秘密。",
        "readingMoodZh": "岛风、碎片、成长的咸味。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Reservoir Books / RTVE 2026-05",
        "sourceUrl": "",
        "selectionReason": "2026年出道长篇，媒体与书店可核。",
        "author": {
            "name": "Lana Corujo",
            "localizedName": "拉娜·科鲁霍",
            "nationality": "西班牙",
            "biographyZh": "Lana Corujo 来自兰萨罗特，先以插画受到关注，后转向小说。她不把岛屿写成旅游明信片，而写成既深爱又会保存伤害的故乡。",
        },
        "fullDescriptionZh": "祖母去玩宾果时，两姐妹总会跑向一座虚构火山，数到三，再赶在大人发现前回来。某个夜晚，熟悉的规则突然改变；此后的人生像一张十五格宾果卡，被内疚、家庭秘密和成长逐格填满。火山不在地图上，却成为姐妹记忆中最真实的地点。",
        "recommendationZh": "最让人记住的不是那座虚构火山，而是两个女孩当年跑向它时的默契，以及多年后再回头时完全不同的心情。小说像在翻一盒没有按年份整理的旧照片，碎片慢慢拼出家庭里没人愿意直说的那一夜。",
        "audienceZh": "喜欢岛屿、姐妹、家庭记忆和非线性成长故事的人会被它打动。想要一条笔直情节线的读者，要给它一点耐心。",
    },
    # ---------- Japanese ----------
    {
        "matchTitle": "ゾンビ回収婦",
        "languageCode": "ja",
        "chineseTitle": "僵尸回收妇",
        "publicationDate": "2026-07-09",
        "isbn13": "9784065441121",
        "publisher": "講談社",
        "primaryGenre": "科幻",
        "genres": ["科幻", "文学小说"],
        "tags": ["芥川奖", "AI", "劳动", "虚拟现实"],
        "coverImage": "/covers/zombie-kaishufu.jpg",
        "editorQuoteZh": "我想告诉你这个世界的秘密——我是这家酒店唯一的扫除妇。",
        "readingMoodZh": "短、冷、虚实叠在一起，劳动像仪式。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "講談社刊记 ISBN 9784065441121；《群像》2026年5月号；2026-07-15筑地新喜乐发表；读卖新闻访谈",
        "sourceUrl": "",
        "selectionReason": "第175回芥川奖获奖作。原刊《群像》2026年5月号，7月9日讲谈社单行本160页，7月15日于东京筑地新喜乐料亭发表。",
        "author": {
            "name": "小砂川チト",
            "localizedName": "小砂川千户",
            "nationality": "日本",
            "biographyZh": "小砂川チト 1990 年生于岩手，以本作获第 175 回芥川奖。她从童年恐怖游戏记忆出发，把有限世界中的微小生活观察转化成奇异而克制的小说。",
        },
        "fullDescriptionZh": "人工智能普及后，主人公失去工作，也被丈夫抛弃。她进入一款以僵尸酒店为舞台的虚拟游戏，成为唯一负责清理和回收尸骸的清扫妇。重复劳动意外带来秩序与快感；当她与一具僵尸产生微妙共鸣，她也开始重新审视自己长期被动、被安排的人生。",
        "recommendationZh": "“在游戏里捡僵尸”听起来荒唐，真正刺人的却是她在现实里早已像个透明人。工作被 AI 取代，婚姻也把她丢下，反而是清理虚拟尸体时，她第一次感觉自己有用。小说怪得很有道理，也把“人必须积极上进吗”问得很坦白。",
        "audienceZh": "关心 AI、失业、劳动价值和虚拟现实的人会读到很多东西。它虽然有僵尸，却不是打怪爽文，而是一部短、冷、很当代的纯文学小说。",
    },
    {
        "matchTitle": "けんぐゎい",
        "languageCode": "ja",
        "chineseTitle": "圈外",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "光文社",
        "primaryGenre": "历史",
        "genres": ["历史", "文学小说"],
        "tags": ["直木奖", "时代小说", "江户"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "圈外的人并非没有故事，只是信号到不了。",
        "readingMoodZh": "时代、痛、却有体温的长篇。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "第175回直木奖 / Kobunsha",
        "sourceUrl": "",
        "selectionReason": "第175回直木奖获奖作，2026年上半年刊行。",
        "author": {
            "name": "朝倉かすみ",
            "localizedName": "朝仓霞",
            "nationality": "日本",
            "biographyZh": "朝倉かすみ 擅长书写生活偏离计划之后，人如何继续走下去。她关注那些被制度和审美放到边缘的人，并以本作获得第 175 回直木奖。",
        },
        "fullDescriptionZh": "江户时代，脸上留有病痕的ふゆ与以容貌为资本的妹妹，在父亲去世后走入完全不同的劳动与命运。性暴力、收养和医者的介入，使ふゆ不断被他人的目光定义；她必须从被排斥的“圈外”，争取一种不以美丑裁定的生存方式。",
        "recommendationZh": "ふゆ的处境离我们并没有因为隔着江户时代就变远。别人先看见她脸上的伤痕，再决定她配得到什么；小说真正要写的，是一个被不断推到圈外的人，怎样一点点夺回解释自己的权利。它很痛，却没有消费这种痛。",
        "audienceZh": "喜欢时代小说，又希望历史题材能真正碰到性别、身体和排斥问题的人，可以读。故事不轻，想找轻松冒险的话不太合适。",
    },
    {
        "matchTitle": "きずもの",
        "languageCode": "ja",
        "chineseTitle": "伤物",
        "publicationDate": "2026-09-30",
        "isbn13": "9784093867887",
        "publisher": "小学館",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["友情", "时间", "北海道报纸连载"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "伤还在，人却被允许再爱一点自己。",
        "readingMoodZh": "长、暖中带刺、新闻连载改成的厚书。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Shogakukan ISBN 9784093867887",
        "sourceUrl": "",
        "selectionReason": "2026年9月30日刊行，ISBN可核。",
        "author": {
            "name": "西加奈子",
            "localizedName": "西加奈子",
            "nationality": "日本",
            "biographyZh": "西加奈子以《サラバ！》获直木奖，小说语言口语感强、情感直接，却不轻易简化人生的困难。本书是她时隔五年的长篇作品。",
        },
        "fullDescriptionZh": "一名小说家与青梅竹马通过社交媒体维持不近不远的联系；另一名女性因一件往事离开日本，前往温哥华与朋友共同生活。两组旧识在时间、距离和生活变化中重新理解彼此。所谓“伤”不是一次事件，而是人与自己长期相处的方式。",
        "recommendationZh": "这本书理解一种成年人都熟悉的关系：没有真正断掉，也没有力气恢复从前，只靠偶尔的消息证明彼此还在。温哥华和日本之间的距离很远，真正难跨过的却是那些年里各自变成的人。",
        "audienceZh": "西加奈子的读者，以及喜欢友情、移居和成年人慢慢修补自己的故事的人，会愿意陪它走完。它不靠悬念催你，要留一点安静给人物。",
    },
    {
        "matchTitle": "永遠の記憶",
        "languageCode": "ja",
        "chineseTitle": "永远的记忆",
        "publicationDate": "2026-08-05",
        "isbn13": "",
        "publisher": "文藝春秋",
        "primaryGenre": "推理",
        "genres": ["推理"],
        "tags": ["伽利略", "汤川学", "系列"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "有些谜不能忘，忘了人就不完整。",
        "readingMoodZh": "本格、系列情感、夏季长篇。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Bungeishunju Galileo series, 2026-08-05",
        "sourceUrl": "",
        "selectionReason": "伽利略系列2026年8月5日最新长篇。",
        "author": {
            "name": "東野圭吾",
            "localizedName": "东野圭吾",
            "nationality": "日本",
            "biographyZh": "東野圭吾是被全球广泛翻译的日本推理作家。伽利略系列以物理学者汤川学的冷静推理对照警方现场，兼顾本格机关与人物情感。",
        },
        "fullDescriptionZh": "刑警内海遭刺伤，一位老人保持沉默，一名年轻女性进入调查视线。汤川与草薙从一件遗物追入一桩“不能被遗忘”的谜案，科学解释与人情旧债再次并行。案件追问的不只是事实如何发生，也是谁有权替别人保存记忆。",
        "recommendationZh": "汤川依旧负责把混乱的问题拆开，草薙负责站在人的现场，但这一次，内海受伤让案件多了一层私人重量。谜题仍然好读，真正留到最后的却可能不是作案方法，而是一个人为什么宁愿沉默，也不肯交出记忆。",
        "audienceZh": "东野圭吾和伽利略系列读者不用犹豫。没读过前作也能进入，只是认识这些人物越久，某些时刻越有分量。",
    },
    {
        "matchTitle": "ファイア・ドーム 上",
        "languageCode": "ja",
        "chineseTitle": "火焰穹顶 上",
        "publicationDate": "2026-06-05",
        "isbn13": "9784093867696",
        "publisher": "小学館",
        "primaryGenre": "推理",
        "genres": ["推理", "社会议题"],
        "tags": ["谣言", "媒体", "地方都市"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "谣言是轻薄的娱乐，烧到人身上却很重。",
        "readingMoodZh": "厚、社会派、上下卷的第一口气。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Shogakukan ISBN 9784093867696",
        "sourceUrl": "",
        "selectionReason": "2026年6月5日刊行，ISBN可核。",
        "author": {
            "name": "辻村深月",
            "localizedName": "辻村深月",
            "nationality": "日本",
            "biographyZh": "辻村深月长期书写青春、家庭与社会事件如何改变普通人。本书以出道二十二年的积累，挑战一部关于舆论与灾难观看的大型长篇。",
        },
        "fullDescriptionZh": "二十五年前，一座地方城市因百货店接待员绑架杀人案陷入舆论狂热。谣言既烧向加害者，也灼伤受害者；当旧事看似冷却，新的事件又把媒体、邻里与家庭重新卷入。上卷铺开的不是一团火，而是一整套让灾难持续燃烧的社会结构。",
        "recommendationZh": "真正可怕的也许不只是一桩旧案，而是一座城怎样围观、转述，再把猜测说成事实。每个人似乎只是多说了一句话，合在一起却足以烧毁一个家庭。上卷很厚，也只负责把火势铺开——这份不急，反而让人不安。",
        "audienceZh": "喜欢社会派推理、辻村深月，以及愿意把时间交给上下卷长篇的人会读得很投入。只想当天看完一个完整谜案的话，先别从它开始。",
    },
    {
        "matchTitle": "探偵小石は戻らない",
        "languageCode": "ja",
        "chineseTitle": "侦探小石不再回来",
        "publicationDate": "2026-09-30",
        "isbn13": "9784093868051",
        "publisher": "小学館",
        "primaryGenre": "推理",
        "genres": ["推理"],
        "tags": ["系列", "逆转", "福冈"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "助手看见的不是名侦探，是站在犯人位置的人。",
        "readingMoodZh": "轻快对白下的本格恶作剧。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Shogakukan ISBN 9784093868051",
        "sourceUrl": "",
        "selectionReason": "2026年9月30日系列续作。",
        "author": {
            "name": "森バジル",
            "localizedName": "森巴吉尔",
            "nationality": "日本",
            "biographyZh": "森バジル 以松本清张奖出道，前作成为 2025—2026 年书店推理热点。她善于兼顾侦探迷式乐趣、人物对话和结构反转。",
        },
        "fullDescriptionZh": "专门调查恋爱纠纷的侦探小石与助手莲杖继续接案，直到莲杖亲眼看见小石站在嫌疑人一边。轻快的侦探事务所日常由此失去安全感：案件尚未解开，两人之间最基本的信任已经先被改写。",
        "recommendationZh": "第一本已经教会读者别太轻信表面，续作干脆把怀疑推到侦探本人身上。小石和莲杖的对话还是好笑，信任却在一点点漏气。它最会玩的不是“谁做的”，而是“你为什么会相信他没做”。",
        "audienceZh": "喜欢本格结构、侦探与助手的默契，以及被作者骗得心服口服的人会很快乐。最好先读前作，但新读者也能感到哪里不对。",
    },
    {
        "matchTitle": "変な地図",
        "languageCode": "ja",
        "chineseTitle": "奇怪的地图",
        "publicationDate": "2025-10-31",
        "isbn13": "9784575248104",
        "publisher": "双葉社",
        "primaryGenre": "悬疑",
        "genres": ["悬疑"],
        "tags": ["解谜", "地图", "视觉"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "先看图，再决定怕什么。",
        "readingMoodZh": "游戏感、视觉、阅读像探险。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "双葉社公式 / ISBN 9784575248104，2025-10-31刊（近12个月内）",
        "sourceUrl": "",
        "selectionReason": "雨穴「変な」系列近作；书店初版2025-10-31，ISBN可核。",
        "author": {
            "name": "雨穴",
            "localizedName": "雨穴",
            "nationality": "日本",
            "biographyZh": "雨穴以《変な家》等作品开拓视觉推理，把平面图从说明材料变成核心证据。他迫使读者盯住细节，并承认自己曾经看漏。",
        },
        "fullDescriptionZh": "地图与文字共同构成谜题。图上的道路、边界与空白并非辅助插图，而是隐藏信息的现场；读者必须反复旋转、对照和检查，才会发现看似普通的空间已经悄悄改变规则。",
        "recommendationZh": "这不是一张看过就翻页的地图。你得盯着道路、空白和比例，甚至把书转个方向，才会意识到自己漏掉了什么。雨穴把“看图”变成真正的破案动作，也把那句“我刚才怎么没发现”变成最有效的惊吓。",
        "audienceZh": "喜欢视觉推理、地图谜题和互动阅读的人会玩得很开心。若你只信文字、不愿来回对照插图，这本书的乐趣会少一大半。",
    },
    {
        "matchTitle": "多類婚姻譚",
        "languageCode": "ja",
        "chineseTitle": "多类婚姻谭",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "講談社",
        "primaryGenre": "爱情",
        "genres": ["爱情", "文学小说"],
        "tags": ["婚姻", "直木候选", "当代"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "结婚若这么难，小说就应该把难写清楚。",
        "readingMoodZh": "认真、对话多、当代伦理。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Kodansha / 第175回直木奖候选",
        "sourceUrl": "",
        "selectionReason": "2026年上半年直木奖候选长篇。",
        "author": {
            "name": "凪良ゆう",
            "localizedName": "凪良悠",
            "nationality": "日本",
            "biographyZh": "凪良ゆう 以《流浪の月》《汝、星のごとく》等作品受到广泛关注。她擅长书写性向、自尊与误解，让人物在温柔之中面对难以和解的现实。",
        },
        "fullDescriptionZh": "几组婚姻与准婚姻被并置书写：入籍前夜的争执、家庭期待、经济压力、性向与代际观念，都让“结婚”不再是单一答案。人物在对话中反复靠近又卡住，没有统一结论，只有各自必须承担的选择。",
        "recommendationZh": "它不问“最后有没有结婚”这种简单问题，而是把镜头留在决定之前：钱怎样分，家人怎么看，身份要不要解释，两个人是否真的想要同一种未来。几场对话没有大喊大叫，却比许多分手戏更紧张。",
        "audienceZh": "凪良ゆう的读者，以及正在思考婚姻、性别和亲密关系的人，会读得很有共鸣。它有爱，但不会把爱写成万能答案。",
    },
    # ---------- Korean ----------
    {
        "matchTitle": "아코디언",
        "languageCode": "ko",
        "chineseTitle": "手风琴",
        "publicationDate": "2026-06-22",
        "isbn13": "9788936439965",
        "publisher": "창비",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "成长"],
        "tags": ["成长", "现实", "长篇"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "十年后再响的那架琴，先经过现实。",
        "readingMoodZh": "沉、吸力强、成长小说的宽河。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Changbi ISBN 9788936439965",
        "sourceUrl": "",
        "selectionReason": "2026年6月22日出版，ISBN可核。",
        "author": {
            "name": "천명관",
            "localizedName": "千明官",
            "nationality": "韩国",
            "biographyZh": "천명관 以强叙事与黑色幽默书写韩国现代社会的欲望和失败，《鲸》使他受到国际关注。本书是他时隔十年的长篇回归。",
        },
        "fullDescriptionZh": "一个少年在严酷现实中长大，逐渐明白什么声音可以被听见，什么愿望只能暂时压下。手风琴既是具体器物，也是他生活的节奏：伸展、挤压、偶尔漏风。每次向前都要穿过劳动、贫穷与运气设下的关口。",
        "recommendationZh": "千明官很会讲故事，你会被少年一路带着往前跑，却在某个转弯突然看见现实早已等在那里。手风琴一拉一收，像他的人生：刚刚有一点展开的空间，又被贫穷和命运挤回去。它好读，但绝不轻巧。",
        "audienceZh": "喜欢千明官、少年成长和粗粝现实的人会一口气读下去。想找温柔治愈的话，这本书给你的更多是力气，不是安慰。",
    },
    {
        "matchTitle": "시간의 감촉",
        "languageCode": "ko",
        "chineseTitle": "时间的触感",
        "publicationDate": "2026-06-22",
        "isbn13": "9791141617226",
        "publisher": "문학동네",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["老年", "姐妹", "时间三部曲"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "六十岁以后，时间开始有皮肤。",
        "readingMoodZh": "慢、准、身体记忆的文学。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Aladin / Kyobo ISBN 9791141617226",
        "sourceUrl": "",
        "selectionReason": "2026年6月22日文学村刊行，纸书ISBN可核。",
        "author": {
            "name": "은희경",
            "localizedName": "殷熙耕",
            "nationality": "韩国",
            "biographyZh": "은희경 自《鸟的礼物》以来持续书写人如何被时间塑造。她擅长从感觉的细小偏差中发现关系变化，本书也完成了她所称的“时间三部曲”。",
        },
        "fullDescriptionZh": "两位性格与外貌迥异的六十岁姐妹，重新碰触彼此分开生活的漫长岁月。旧误解没有自动消失，衰老的身体却带来新的感受与第一次。时间不再是抽象主题，而成为能被触摸、误记和重新理解的东西。",
        "recommendationZh": "很多小说把六十岁写成回望，这本却还在写“第一次”。姐妹再次靠近时，身体已经和年轻时不同，记忆也各有版本。它没有大哭大笑，只是把一句话里的迟疑、一次触碰里的陌生写得特别准确。",
        "audienceZh": "喜欢姐妹故事、老年主题和细腻韩语文学的人会读得很静。它不催你翻页，需要你愿意慢一点，听人物把话说完。",
    },
    {
        "matchTitle": "찌니주의보",
        "languageCode": "ko",
        "chineseTitle": "蕾丝注意报",
        "publicationDate": "2026-09-01",
        "isbn13": "",
        "publisher": "창비",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "社会议题"],
        "tags": ["乡村", "酷儿", "邻里"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "偏见先到饭桌，理解有时也从饭桌来。",
        "readingMoodZh": "人间、对话、山村的慢热。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Changbi / Maeil Business 2026-09",
        "sourceUrl": "",
        "selectionReason": "2026年9月前后刊行，书评可核。",
        "author": {
            "name": "정지아",
            "localizedName": "郑芝雅",
            "nationality": "韩国",
            "biographyZh": "정지아 长于书写全罗道土地与历史余波。《父亲的解放日记》使她拥有更广泛读者；她始终坚持不把人物写成议题标签，而写成会共同生活的人。",
        },
        "fullDescriptionZh": "平均年龄七十八岁的水平村迎来三十多岁的成珍与惠珍。两人的同性伴侣关系传开后，村里有人排斥、有人维护，也有人只是从远处打量。变化不靠一场宏大冲突，而从闲话、饭桌和邻里之间慢慢移动的距离发生。",
        "recommendationZh": "这本书好在没有把村民简单分成善人与坏人。有人排斥，有人帮忙，也有人只是嘴碎；可第二天大家仍会在同一张饭桌、同一条村路上碰见。成珍与惠珍的关系因此不再是一道口号，而是这个村子必须学会面对的生活。",
        "audienceZh": "关心乡村、老龄化和性少数生活，又不喜欢说教式议题小说的人，会喜欢这种慢慢变近的写法。",
    },
    {
        "matchTitle": "서리꽃",
        "languageCode": "ko",
        "chineseTitle": "霜花",
        "publicationDate": "2026-08-24",
        "isbn13": "9791167141644",
        "publisher": "해냄출판사",
        "primaryGenre": "历史",
        "genres": ["历史", "文学小说"],
        "tags": ["大河", "赵廷来"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "霜落在花上，历史仍要人去走。",
        "readingMoodZh": "大、传统、国民作家的长河。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "해냄 서리꽃 1권 ISBN 9791167141644",
        "sourceUrl": "",
        "selectionReason": "赵廷来2026年8月24日刊行，第1卷ISBN可核。",
        "author": {
            "name": "조정래",
            "localizedName": "赵廷来",
            "nationality": "韩国",
            "biographyZh": "조정래 以《太白山脉》《阿里郎》《汉江》构成韩国近现代史的重要文学地图。他擅长写人群、土地与政治力量如何共同改变个人命运。",
        },
        "fullDescriptionZh": "“霜花”把短暂与坚硬放在同一意象里。网站现有资料只确认小说延续赵廷来将个人置于大历史中的写法，尚不足以准确交代人物和事件；正式上线前需依据出版社勒口补足卷一的主角、年代与核心冲突。",
        "recommendationZh": "赵廷来的小说从来不是让人随手翻几页的，它更像请你坐下来，陪一群人走过一段很长的历史。现有资料还没把卷一的人物和年代说清楚，正式上线前必须补足；否则只谈“史诗感”，对读者并不诚实。",
        "audienceZh": "读过赵廷来、喜欢韩国近现代史和大河群像的人可以关注。若你只想找一本短、快、立刻给答案的书，它不会配合。",
    },
    {
        "matchTitle": "절창",
        "languageCode": "ko",
        "chineseTitle": "绝唱",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "위즈덤하우스",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "文学小说"],
        "tags": ["具竝模", "声音", "黑暗"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "绝唱不是赞美，是把声音用到尽头。",
        "readingMoodZh": "暗、准、文学恐怖的边缘。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Wisdom House / 2026 lists",
        "sourceUrl": "",
        "selectionReason": "具竝模2026年新作，畅销榜可见；ISBN待核。",
        "author": {
            "name": "구병모",
            "localizedName": "具竝模",
            "nationality": "韩国",
            "biographyZh": "구병모 长期书写少年、制度与身体极限，语言冷而精确。她把惊悚当作伦理问题，而非单纯制造刺激的工具。",
        },
        "fullDescriptionZh": "“绝唱”暗示声音与生命被推到边缘的时刻。网站现有资料只能确认作品延续具竝模对黑暗青春、身体与制度压力的关注，尚不能安全补写具体角色和事件。上线前应由编辑依据正式书讯完善梗概。",
        "recommendationZh": "具竝模最擅长的，是让一个本来很好听的词慢慢露出刀口。“绝唱”究竟属于谁、为什么唱到最后，现有资料还不能回答，因此不该装作知道。但只要熟悉她的写作，就会明白这大概不是一首会让人轻松听完的歌。",
        "audienceZh": "喜欢具竝模、文学惊悚和黑暗青春题材的人可以等资料补齐后再读。想被安慰的话，她通常不是最温柔的选择。",
    },
    {
        "matchTitle": "한국사 이상현상 연구원",
        "languageCode": "ko",
        "chineseTitle": "韩国史异常现象研究院",
        "publicationDate": "2026-08-31",
        "isbn13": "9791124137635",
        "publisher": "다이브",
        "primaryGenre": "科幻",
        "genres": ["科幻", "奇幻"],
        "tags": ["历史异常", "类型", "网文出身"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "历史若出现异常，研究院比教科书先上班。",
        "readingMoodZh": "巧、类型、知识游戏。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Aladin / Kyobo ISBN 9791124137635，다이브 2026-08-31",
        "sourceUrl": "",
        "selectionReason": "2026年8月31日刊行，ISBN可核。",
        "author": {
            "name": "최인서",
            "localizedName": "崔仁叙",
            "nationality": "韩国",
            "biographyZh": "최인서 从网络类型写作进入纸书市场，擅长把历史知识转换成异常事件。文笔服务设定，设定则直接服务阅读快感。",
        },
        "fullDescriptionZh": "韩国历史中不断出现本不该存在的异常现象，一个专门机构负责调查、处理，或把它们继续保密。工作人员在史实与怪异之间穿梭，每一次任务都迫使他们重新判断：教科书留下的是事实，还是被整理过的版本？",
        "recommendationZh": "“如果历史出了 bug，谁负责修？”这个念头本身就很有趣。小说把教科书里的年代和人物变成研究员每天要处理的异常工单，既有职场喜感，也会让人重新回头看那些自以为熟悉的历史。",
        "audienceZh": "喜欢韩国史、异常机构、规则怪谈和设定型小说的人，会很快进入这个世界。即使历史知识不深，也能先跟着任务走。",
    },
    {
        "matchTitle": "인비인",
        "languageCode": "ko",
        "chineseTitle": "隐形人",
        "publicationDate": "2026-06-19",
        "isbn13": "9791172134297",
        "publisher": "한겨레출판",
        "primaryGenre": "惊悚",
        "genres": ["惊悚", "文学小说"],
        "tags": ["奇谭", "短篇", "成海娜"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "看不见的人，往往最先被消费。",
        "readingMoodZh": "短、凉、九个故事的鬼气。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Aladin / Kyobo ISBN 9791172134297",
        "sourceUrl": "",
        "selectionReason": "2026年6月19日刊行的第一本奇谭集，ISBN可核。",
        "author": {
            "name": "성해나",
            "localizedName": "成海娜",
            "nationality": "韩国",
            "biographyZh": "성해나 的文字冷、准，对真实与伪装的边界极为敏感。本书是她的首部奇谭集，以类型外壳继续审视当代人的无心。",
        },
        "fullDescriptionZh": "九篇奇谭被分入昨日、今日与明日：有人消失，有人冷眼旁观，也有人把别人的灾难当作电影观看。每篇都先让读者接受一套规则，再突然翻转它。所谓“隐形”不是超能力，而是社会选择对某些人视而不见。",
        "recommendationZh": "九个故事里未必都有传统意义上的鬼，真正让人后背发凉的，往往是旁人那句“我没注意”。昨天、今天和明天换了布景，人选择看不见别人的习惯却没有消失。它短，冷意却留得很久。",
        "audienceZh": "爱读短篇、奇谭和不靠血腥取胜的文学恐怖，可以慢慢读这九篇。只想沉进一条长故事线的人，可能会觉得每次结束得太快。",
    },
    {
        "matchTitle": "테니스 나무",
        "languageCode": "ko",
        "chineseTitle": "网球树",
        "publicationDate": "2026-09-04",
        "isbn13": "9791141603618",
        "publisher": "문학동네",
        "primaryGenre": "推理",
        "genres": ["推理", "文学小说"],
        "tags": ["达格奖", "尹高银"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "树还在，球的落点已经改了。",
        "readingMoodZh": "冷、准、犯罪与日常的缝。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "문학동네 ISBN 9791141603618",
        "sourceUrl": "",
        "selectionReason": "2026年9月4日刊行，ISBN可核。",
        "author": {
            "name": "윤고은",
            "localizedName": "尹高银",
            "nationality": "韩国",
            "biographyZh": "윤고은 是少数获得英国犯罪作家协会达格奖的韩国作者。她写罪案时保留文学侧面，异常从来不是突然降临，而是早已埋伏在日常秩序中。",
        },
        "fullDescriptionZh": "网球与树构成一个看似悠闲的意象，犯罪却悄悄进入观察与日常。网站现有资料尚未给出足够具体的案件、人物和行动线；正式上线前应根据出版社书讯补充。可以保留的阅读预期是：普通世界先被建立，规则随后在不动声色中改变。",
        "recommendationZh": "尹高银的小说常常先让你相信一切正常，再在很小的地方改动规则。等你意识到不对，日常已经无法恢复原状。遗憾的是现有资料连人物和案件都没说清，正式页面应该先把故事讲明白，再谈她的“冷静”。",
        "audienceZh": "喜欢文学推理、慢慢发作的不安和尹高银旧作的人可以关注。若你需要每章一个反转，它大概不会那么热闹。",
    },
    # ---------- French ----------
    {
        "matchTitle": "Le Crime du paradis",
        "languageCode": "fr",
        "chineseTitle": "天堂里的罪",
        "publicationDate": "2026-03-03",
        "isbn13": "9782702192979",
        "publisher": "Calmann-Lévy",
        "primaryGenre": "推理",
        "genres": ["推理", "悬疑"],
        "tags": ["谁是凶手", "蓝色海岸", "1928"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "天堂别墅里，人人都像嫌疑犯。",
        "readingMoodZh": "封闭、阳光、旧式解谜的快乐。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Calmann-Lévy / ISBN 9782702192979",
        "sourceUrl": "",
        "selectionReason": "2026年3月3日出版，ISBN可核。",
        "author": {
            "name": "Guillaume Musso",
            "localizedName": "纪尧姆·穆索",
            "nationality": "法国",
            "biographyZh": "Guillaume Musso 是法国最具读者号召力的畅销小说家之一，擅长用阳光、秘密和最终翻面制造阅读速度。本书延续他让复杂谜局保持易读的能力。",
        },
        "fullDescriptionZh": "1928 年，安提布角一座豪华别墅中，美国富豪夫妇的三岁儿子突然失踪。警察面对的是彼此矛盾的证词和一屋各怀秘密的宾客；年轻作家 Agatha Harding 则试图把这场真实悲剧写成畅销故事。地中海阳光之下，每个人都有值得怀疑的动机。",
        "recommendationZh": "阳光、海风和豪宅，本该让人放松，却因为一个孩子的失踪忽然都变得可疑。它有老式侦探小说的乐趣：一屋子人，一连串谎话，一个谁都不能轻易离开的现场。读起来顺，也很会吊胃口。",
        "audienceZh": "穆索读者、法语悬疑入门者，以及一看到“所有人都有嫌疑”就忍不住往下读的人，会喜欢。",
    },
    {
        "matchTitle": "L'Adolescence du perroquet",
        "languageCode": "fr",
        "chineseTitle": "鹦鹉的青春期",
        "publicationDate": "2026-08-19",
        "isbn13": "9782226513045",
        "publisher": "Albin Michel",
        "primaryGenre": "文学小说",
        "genres": ["文学小说"],
        "tags": ["寓言", "诺东", "秋季"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "爱不是应得的，鹦鹉比人先把这点说出来。",
        "readingMoodZh": "短、讽、诺东式寓言。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Albin Michel ISBN 9782226513045",
        "sourceUrl": "",
        "selectionReason": "2026年8月19日秋季例行新作。",
        "author": {
            "name": "Amélie Nothomb",
            "localizedName": "阿梅丽·诺冬",
            "nationality": "比利时",
            "biographyZh": "Amélie Nothomb 的年度新作已成为法语出版日历的一部分。她惯于用简短句子处理自尊、权力和不对等关系，本书则把家庭剧压缩进人与鹦鹉之间。",
        },
        "fullDescriptionZh": "电台评论员阿尔邦收养了一只非洲灰鹦鹉。最初的喂养逐渐变成亲职，亲职又滑向控制；小小公寓最终成了人与鸟争夺话语权的青春期战场。一只会模仿人声的鸟，把爱、亏欠与支配逼到既滑稽又残酷的位置。",
        "recommendationZh": "这只鹦鹉会说人话，却也把人的控制欲照得格外清楚。书很短，笑点来得快，冷意来得更快。读完像听见一个刻薄又准确的家庭笑话，笑过之后仍有点不舒服。",
        "audienceZh": "喜欢诺冬、荒诞寓言和关系里微妙权力游戏的人，可以一口气读完。想看厚重写实长篇的话，它不是那一路。",
    },
    {
        "matchTitle": "Fauves",
        "languageCode": "fr",
        "chineseTitle": "猛兽",
        "publicationDate": "2026-01-07",
        "isbn13": "",
        "publisher": "Albin Michel",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "历史"],
        "tags": ["马戏团", "八〇年代", "成长"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "驯狮之前，先要承认自己也是兽。",
        "readingMoodZh": "汗、血、帐篷里的光与暗。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Albin Michel / Le Figaro 2026-01",
        "sourceUrl": "",
        "selectionReason": "2026年1月7日出版。",
        "author": {
            "name": "Mélissa Da Costa",
            "localizedName": "梅丽莎·达科斯塔",
            "nationality": "法国",
            "biographyZh": "Mélissa Da Costa 是近年来法国极受欢迎的小说家，擅长在通俗情感和较硬题材之间切换。本书把她熟悉的情感推动力带进 1980 年代马戏团。",
        },
        "fullDescriptionZh": "17 岁的托尼与父亲决裂后，进入一支巡回马戏团，从最不起眼的杂务做起，逐渐靠近狮子与豹。帐篷亮起时，马戏是童话；散场以后，汗、伤口和父权规则才显露出来。少年必须在真实危险中学习，人究竟怎样证明自己长大。",
        "recommendationZh": "托尼不是在课堂里长大，而是在兽笼、汗味和一次次逞强中长大。马戏团的光很好看，灯灭后的生活却一点也不浪漫。小说有很强的故事性，也没有替那个年代的暴力找借口。",
        "audienceZh": "如果你爱读少年成长、特殊职业和巡回马戏团，这本很有吸引力。介意动物表演或粗粝场面，最好先了解题材。",
    },
    {
        "matchTitle": "C'était ça ou mourir",
        "languageCode": "fr",
        "chineseTitle": "要么这样要么死",
        "publicationDate": "2026-08-01",
        "isbn13": "",
        "publisher": "Grasset",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "悬疑"],
        "tags": ["龚古尔初选", "秋季"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "标题已经把选择压缩成一口气。",
        "readingMoodZh": "紧、当代、奖项季的热度。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Grasset / Goncourt first selection 2026",
        "sourceUrl": "",
        "selectionReason": "2026秋季龚古尔初选，法国畅销可见。",
        "author": {
            "name": "Thélyson Orélien",
            "localizedName": "泰利松·奥雷利安",
            "nationality": "海地/加拿大",
            "biographyZh": "Thélyson Orélien 以法语写作，本书进入 2026 年龚古尔奖初选。作者的详细生平仍建议依据出版社资料复核，避免以奖项曝光代替准确介绍。",
        },
        "fullDescriptionZh": "标题把人物推到没有退路的选择前：接受眼前唯一可行的道路，或者付出生命代价。网站现有资料显示作品涉及生存、迁移或暴力等当代议题，但尚不足以安全补写具体人物与事件；正式上线前应以出版社书讯核对完整梗概。",
        "recommendationZh": "光看标题，就知道这不是一本会轻声安慰人的书。它把人物逼到选择只剩两面的地方，也把读者带进法语秋季文学最紧绷的一种声音。只是目前资料不够，宁愿先把话说到这里，也不拿模糊主题冒充故事。",
        "audienceZh": "关注法语秋季文学、愿意面对迁移、生存或暴力等沉重议题的人可以留意。它显然不是一本度假消遣。",
    },
    {
        "matchTitle": "L'Autre moi",
        "languageCode": "fr",
        "chineseTitle": "另一个我",
        "publicationDate": "2026-04-28",
        "isbn13": "",
        "publisher": "Fleuve",
        "primaryGenre": "惊悚",
        "genres": ["惊悚", "悬疑"],
        "tags": ["高概念", "蒂利耶"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "现实若开始渗漏，侦探小说也会做梦。",
        "readingMoodZh": "迷宫、脑内、一层层翻面。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Fleuve, 2026-04-28",
        "sourceUrl": "",
        "selectionReason": "2026年4月28日独立长篇。",
        "author": {
            "name": "Franck Thilliez",
            "localizedName": "弗兰克·蒂利耶",
            "nationality": "法国",
            "biographyZh": "Franck Thilliez 是法国高概念惊悚的代表作家，常把科学假说、警察程序与噩梦体验叠合。本书暂离熟悉的系列人物，转向更独立、更迷宫式的故事。",
        },
        "fullDescriptionZh": "一条叙事中，熟悉日常开始悄悄失真；另一条叙事中，悬崖下的无名女尸等待身份与死因被查明。两条线彼此渗透，梦境、记忆和调查程序不断交换位置，读者也逐渐失去可以依赖的确定答案。",
        "recommendationZh": "它不只问“谁杀了她”，还会让你怀疑自己刚刚读到的现实究竟算不算数。两条线越靠越近，脚下的地面越不可靠。喜欢在小说里迷路的人，会享受这种大脑被不断翻面的感觉。",
        "audienceZh": "蒂利耶读者、多线惊悚和认知迷局爱好者会很过瘾。只想轻轻松松猜个凶手，可能会被它绕得有点累。",
    },
    {
        "matchTitle": "Je suis drôle",
        "languageCode": "fr",
        "chineseTitle": "我很有趣",
        "publicationDate": "2026-04-01",
        "isbn13": "",
        "publisher": "Gallimard",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["福恩基诺斯", "幽默"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "自称有趣的人，往往正在求救。",
        "readingMoodZh": "轻、准、带一点忧伤的好读。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Gallimard spring 2026",
        "sourceUrl": "",
        "selectionReason": "2026年春 Gallimard 新作；精确日待核。",
        "author": {
            "name": "David Foenkinos",
            "localizedName": "达维德·福恩基诺斯",
            "nationality": "法国",
            "biographyZh": "David Foenkinos 长于书写感情、自尊与自我解嘲，语言流畅而不炫技。他常从看似轻巧的处境出发，抵达人物不愿承认的脆弱。",
        },
        "fullDescriptionZh": "主人公习惯用幽默证明自己的价值，也用笑话避开真正需要面对的感情。随着人物关系靠近，机智逐渐变成防御，笑声停止后的安静反而暴露出更深的难堪与孤独。",
        "recommendationZh": "有些人越会逗大家笑，越不知道怎样认真说一句“我很难过”。这本书写的正是笑话落地后的那几秒安静。它不沉重，却把幽默为什么会成为盔甲写得很准。",
        "audienceZh": "喜欢人物关系、轻微讽刺和带一点忧伤的好读法语小说，可以选它。想要大反转或强刺激，就别抱错期待。",
    },
    {
        "matchTitle": "La révolte de la reine",
        "languageCode": "fr",
        "chineseTitle": "女王的反叛",
        "publicationDate": "2026-03-04",
        "isbn13": "",
        "publisher": "Hugo Publishing",
        "primaryGenre": "爱情",
        "genres": ["爱情", "历史"],
        "tags": ["浪漫", "历史改写", "三部曲"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "王后的轮廓还在，命运被重写了。",
        "readingMoodZh": "华丽、快、浪漫历史。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Hugo Publishing, 2026-03",
        "sourceUrl": "",
        "selectionReason": "2026年3月出版的畅销浪漫第一部。",
        "author": {
            "name": "Morgane Moncomble",
            "localizedName": "摩根·蒙孔布尔",
            "nationality": "法国",
            "biographyZh": "Morgane Moncomble 从网络写作成长为法国畅销浪漫小说家，擅长高浓度情感与快速节奏。本书开启新的历史改写系列，仍保持她鲜明的读者导向。",
        },
        "fullDescriptionZh": "以玛丽·安托瓦内特为灵感的历史改写中，宫廷、欲望与权力共同构成一套严密规则。女主角既要爱，也要赢，还要在别人替她规定的身份中找到可以反抗的裂缝。作为系列开篇，本书负责铺开人物关系与更大的女性谱系。",
        "recommendationZh": "宫廷够华丽，情感够浓，野心也一点不含蓄。好看之处在于，女王不再只是史书里等待结局的人，她也会试着抢回决定自己故事的权利。读感像一部制作精良的历史连续剧。",
        "audienceZh": "爱看宫廷、爱情、女性反叛和历史改写的人会读得很快。考据党请记得：这是小说，不是传记。",
    },
    {
        "matchTitle": "Nous aussi",
        "languageCode": "fr",
        "chineseTitle": "我们也是",
        "publicationDate": "2026-08-01",
        "isbn13": "",
        "publisher": "Actes Sud",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "社会议题"],
        "tags": ["龚古尔初选", "集体"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "两个字的标题，把“我”改成“我们”。",
        "readingMoodZh": "集体、当代、奖项季的锋利。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Actes Sud / Goncourt 2026 first selection",
        "sourceUrl": "",
        "selectionReason": "2026秋季龚古尔初选。",
        "author": {
            "name": "Anne Godard",
            "localizedName": "安娜·戈达尔",
            "nationality": "法国",
            "biographyZh": "Anne Godard 的这部长篇进入 2026 年龚古尔奖初选。现有网站资料不足以支撑更细生平，建议上线前以 Actes Sud 官方作者页复核。",
        },
        "fullDescriptionZh": "“我们也是”把原本私人的经验推向集体发声。网站现有资料仅能确认作品关注当代共同处境，并具有政治与情感两重力度；具体人物、事件与叙事线仍需根据出版社书讯补充后再上线。",
        "recommendationZh": "“我们”是个温暖的词，也可能是一道把人挡在外面的门。这本书真正值得期待的，是它追问谁能说“我们”、谁又总被排除在外。目前情节资料有限，先保留这份问题意识，不替原书编故事。",
        "audienceZh": "关注当代法语文学、公共议题和秋季奖项的人可以留意。偏爱轻快类型故事的话，可能不是最佳入口。",
    },
    # ---------- Italian ----------
    {
        "matchTitle": "I convitati di pietra",
        "languageCode": "it",
        "chineseTitle": "石客",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Einaudi",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "悬疑"],
        "tags": ["斯特雷加", "命运契约"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "毕业之后，契约比友谊更记得你。",
        "readingMoodZh": "文学、命运游戏、奖项的重量。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Einaudi / Strega 2026 reports",
        "sourceUrl": "",
        "selectionReason": "2026斯特雷加相关新书；精确日期待核。",
        "author": {
            "name": "Michele Mari",
            "localizedName": "米歇尔·马里",
            "nationality": "意大利",
            "biographyZh": "Michele Mari 是备受意大利文学读者尊敬的作家，以博学、幻想和对记忆的执着著称。他的作品句子密，幽默也常带着阴影。",
        },
        "fullDescriptionZh": "一群人毕业时立下的诅咒式契约，在多年后仍把他们绑在一起。“石头客人”的神话意象进入当代生活：有人仍记得承诺，有人以为毕业就意味着债务已经结束。往日记忆逐渐变成一份无人能够轻易注销的账。",
        "recommendationZh": "毕业通常意味着散场，这群人却发现，当年说过的话并不会因为离开校园就失效。石客像一位从旧神话里走来的讨债人，让记忆一件件变成现实。它不好读得轻松，却会让人想起自己也曾把哪些承诺留在过去。",
        "audienceZh": "喜欢意大利纯文学、神话改写和 Michele Mari 的读者，会享受它的密度。若你需要线性、快速而明白的情节，这本可能太绕。",
    },
    {
        "matchTitle": "Una splendida rovina",
        "languageCode": "it",
        "chineseTitle": "一座华丽的废墟",
        "publicationDate": "2026-09-01",
        "isbn13": "9788806270995",
        "publisher": "Einaudi",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["乡村幻想", "爱情", "当代讽刺"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "买下一座没有窗户的房子，像买下一场误会。",
        "readingMoodZh": "讽刺、凉、三十岁的自我发明。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Einaudi ISBN 9788806270995",
        "sourceUrl": "",
        "selectionReason": "2026秋季 Einaudi 出版。",
        "author": {
            "name": "Vincenzo Latronico",
            "localizedName": "温琴佐·拉特罗尼科",
            "nationality": "意大利",
            "biographyZh": "Vincenzo Latronico 因《完美》受到国际关注，善于写当代中产如何经营形象，又如何被自己的审美欺骗。他观察精准，很少提供廉价同情。",
        },
        "fullDescriptionZh": "一对刚相爱的三十岁恋人买下波罗的海边一幢一千二百平方米的废屋：没有窗，屋顶勉强完整，所在村庄只有一百九十二人。装修、资金、邻里和热情相继出现裂缝；这次出逃究竟是勇敢的新生活，还是被房产网站美图诱发的共同幻觉？",
        "recommendationZh": "两个人以为自己买的是新生活，交房时才发现连窗户都没有。修屋的每一笔钱、每一次争吵，都在检验他们究竟爱的是彼此，还是自己想象中那个勇敢、自由的版本。它很好笑，也很残忍，因为这种逃离都市的梦实在太熟悉。",
        "audienceZh": "喜欢当代生活讽刺、居住议题和“成年人认真把自己骗了”的故事，会读得很有共鸣。别把它当作海边修房治愈文学。",
    },
    {
        "matchTitle": "Gli anni in bianco e nero",
        "languageCode": "it",
        "chineseTitle": "黑白岁月",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "North",
        "primaryGenre": "家庭",
        "genres": ["家庭", "历史"],
        "tags": ["普利亚", "畅销"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "彩色到来之前，村子已经把人分成明暗。",
        "readingMoodZh": "温暖、群体、通俗历史日常。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "North / 2026 Italian bestseller lists",
        "sourceUrl": "",
        "selectionReason": "2026年意大利畅销前列新作。",
        "author": {
            "name": "Francesca Giannone",
            "localizedName": "弗朗西斯卡·贾诺内",
            "nationality": "意大利",
            "biographyZh": "Francesca Giannone 因《女邮差》成为近年意大利广受欢迎的作者。她善于书写南方村庄、劳动女性与缓慢却真实的社会变化。",
        },
        "fullDescriptionZh": "一个社群被放回彩色摄影尚未普及的年代。村庄规则、女性劳动、阶层之间可见与不可见的界线，构成长篇的日常纹理。人物并非历史名人，时代却通过他们做的饭、走的路和不能说的话逐渐显形。",
        "recommendationZh": "它写的不是“从前真好”，而是从前的人怎样工作、忍耐、争吵，又怎样一点点把日子往前推。人物多，却各有体温；历史没有站在远处讲课，而是落在厨房、邮路和女人每天重复的劳动里。",
        "audienceZh": "读过《女邮差》，或者喜欢南方村庄、女性群像和好读的历史长篇，这本会是很自然的下一站。",
    },
    {
        "matchTitle": "Calde le pere",
        "languageCode": "it",
        "chineseTitle": "热梨",
        "publicationDate": "2026-08-28",
        "isbn13": "9791223286869",
        "publisher": "Giunti",
        "primaryGenre": "历史",
        "genres": ["历史", "文学小说"],
        "tags": ["遗作", "雷诺河", "地方志"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "一声叫卖，把整条河叫回来。",
        "readingMoodZh": "短、地方、遗作的清亮。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Giunti ISBN 9791223286869，2026-08-28 posthumous",
        "sourceUrl": "",
        "selectionReason": "2026年8月28日遗作出版。",
        "author": {
            "name": "Francesco Guccini",
            "localizedName": "弗朗切斯科·古奇尼",
            "nationality": "意大利",
            "biographyZh": "Francesco Guccini 是意大利重要的创作歌手、散文家和小说家，长期书写故乡、河流与口头传统。本书是他生命末期完成的作品。",
        },
        "fullDescriptionZh": "炎热午后，一个骑自行车的女孩沿路喊着“热梨”，由此牵出雷诺河、卡萨莱基奥和一位贞洁少女的地方传闻。故事以短画面推进，妓女与后来近似妇科医生的女性彼此映照。真正连缀全书的不是谜案，而是河流与口头记忆。",
        "recommendationZh": "古奇尼写地名时，像在叫熟人的名字。雷诺河、炎热的空气和街头叫卖声共同把一个地方叫回来。故事不长，也没有刻意煽情，却因为是生命末期的作品，每个寻常细节都多了一点告别的意味。",
        "audienceZh": "Guccini 的听众、喜欢地方故事和口述传统的人，会听见文字里的声音。若你需要复杂情节，它更像一首歌，而不是一部大戏。",
    },
    {
        "matchTitle": "Malinconico Blues",
        "languageCode": "it",
        "chineseTitle": "忧郁蓝调",
        "publicationDate": "2026-09-22",
        "isbn13": "9788806264697",
        "publisher": "Einaudi",
        "primaryGenre": "推理",
        "genres": ["推理", "家庭"],
        "tags": ["律师", "那不勒斯", "幽默"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "律师想降档生活，案件偏不让。",
        "readingMoodZh": "贫嘴、温暖、那不勒斯的日常罪案。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Einaudi ISBN 9788806264697",
        "sourceUrl": "",
        "selectionReason": "2026年9月22日系列新作。",
        "author": {
            "name": "Diego De Silva",
            "localizedName": "迭戈·德席尔瓦",
            "nationality": "意大利",
            "biographyZh": "Diego De Silva 以 Vincenzo Malinconico 系列写出独特的意大利式幽默罪案。主人公总会把事情弄糟，却因此像一个真实而熟悉的朋友。",
        },
        "fullDescriptionZh": "律师 Malinconico 想离开声名显赫的律所，回到失败却自在的生活节奏。一个英俊而平庸的演员前来处理离婚，很快又卷入更严重的指控；伴侣、顾问和一只突然出现的狗，让调查不断偏离原定方向。",
        "recommendationZh": "Malinconico 总想把生活过简单一点，生活却不断把新麻烦推到他桌上。离婚案、严重指控、伴侣和一只狗搅在一起，听起来很乱，读起来却像一段即兴蓝调：案件给节拍，跑题和贫嘴才是旋律。",
        "audienceZh": "喜欢幽默法律小说、那不勒斯日常和会把自己弄得一团糟的系列主人公，可以读。硬派 noir 读者可能会嫌它心太软。",
    },
    {
        "matchTitle": "La ragazzina",
        "languageCode": "it",
        "chineseTitle": "那个小姑娘",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Feltrinelli",
        "primaryGenre": "历史",
        "genres": ["历史", "文学小说"],
        "tags": ["贞德", "坎皮耶洛", "女声"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "圣女之前，她只是一个不肯变小的女孩。",
        "readingMoodZh": "短、烈、历史被写成当下。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Feltrinelli / Campiello 2026 cinquina",
        "sourceUrl": "",
        "selectionReason": "2026坎皮耶洛决赛作品。",
        "author": {
            "name": "Valeria Parrella",
            "localizedName": "瓦莱里娅·帕雷拉",
            "nationality": "意大利",
            "biographyZh": "Valeria Parrella 长期书写那不勒斯、教育、女性与公共勇气。她的句子短、立场清，本书把贞德从圣像中重新带回人的尺度。",
        },
        "fullDescriptionZh": "贞德骑马、祈祷、穿男装，并把太子送上王位。小说不断把她从“圣女”“疯子”与民族象征中还原出来：在历史定义她之前，她也是有母亲、兄弟和梦的少女。围城与战争没有因年代久远而变得陌生。",
        "recommendationZh": "我们太熟悉“圣女贞德”，反而容易忘记她首先是一个非常年轻的女孩。这本书把圣像上的金光擦掉，让她重新骑马、害怕、坚持，也让读者看见：一个女孩一旦表现得过于确信，周围的权力便急着说她疯了。",
        "audienceZh": "喜欢历史文学、女性主义和短而有力的政治性小说，会被它击中。它不是铺陈华丽的宫廷长篇，而像一封写给今天的信。",
    },
    {
        "matchTitle": "Il Bufalo e Sammarzano",
        "languageCode": "it",
        "chineseTitle": "水牛与萨马扎诺",
        "publicationDate": "2026-10-13",
        "isbn13": "",
        "publisher": "Rizzoli",
        "primaryGenre": "推理",
        "genres": ["推理"],
        "tags": ["那不勒斯", "美食", "新系列"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "厨师不说话，菜会替他作证。",
        "readingMoodZh": "香、闹、罪案混着风俗喜剧。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "ANSA 2026-08-07 / Rizzoli 秋季预告",
        "sourceUrl": "",
        "selectionReason": "2026年10月中旬刊行预告；ISBN尚未公布，封面待补。",
        "author": {
            "name": "Maurizio de Giovanni",
            "localizedName": "毛里齐奥·德乔瓦尼",
            "nationality": "意大利",
            "biographyZh": "Maurizio de Giovanni 以那不勒斯罪案系列闻名，产量丰富且地方感稳定。他既能写历史 noir，也善于把当代城市的人情与食物写入调查。",
        },
        "fullDescriptionZh": "一位脾气不佳的那不勒斯厨师习惯用菜表达自己，却意外进入一宗调查。厨房节奏、街区闲谈与案件线索彼此交错；有人沉默，有人饶舌，也有人负责通过味道发现异常。作为系列开篇，本书先建立人物与城市，再让罪案点燃它们。",
        "recommendationZh": "很多罪案小说先给尸体，这一本先让厨房开火。菜怎么做、客人怎么说话、街区里谁认识谁，都可能比正式证词更有用。危险并没有被食物冲淡，反而因为发生在热气腾腾的日常里，更有那不勒斯的味道。",
        "audienceZh": "喜欢美食推理、城市风俗和不那么阴沉的罪案故事，可以从这里认识新系列。De Giovanni 的老读者也会很快认出他的地方感。",
    },
    {
        "matchTitle": "Ci basterà mangiare il vento",
        "languageCode": "it",
        "chineseTitle": "我们吃风就够了",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Mondadori",
        "primaryGenre": "成长",
        "genres": ["成长", "家庭"],
        "tags": ["旅行", "自我", "畅销"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "吃风，是一种把轻当成勇气的说法。",
        "readingMoodZh": "轻、旅行、自我成长的口语。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Mondadori / 2026 Italian charts",
        "sourceUrl": "",
        "selectionReason": "2026年意大利畅销前列新作。",
        "author": {
            "name": "Gianluca Gotto",
            "localizedName": "詹卢卡·戈托",
            "nationality": "意大利",
            "biographyZh": "Gianluca Gotto 长期书写旅行、自我与年轻人的生活选择，作品介于小说、游记和生活思考之间。他的文字明白，读者门槛较低。",
        },
        "fullDescriptionZh": "“吃风就够了”像一句把不稳定生活说成自由的宣言。人物在新加坡、都灵及其他城市之间移动，试图用旅行、爱情和自我叙述回答下一步往哪里走。网站现有资料未提供完整人物线，上线前宜依据出版社简介补足具体起点与核心转折。",
        "recommendationZh": "“靠风活着”听上去很自由，也可能只是年轻人替不安定找的一个漂亮说法。旅行能不能真的改变生活，这本书应该会给出自己的回答。不过现有资料还没有把主人公和关键转折讲清楚，正式上线前需要先补故事，再谈共鸣。",
        "audienceZh": "喜欢旅行、自我成长和容易进入的意大利语原版小说，可以留意。想找厚重文学或黑暗故事的人，可能会觉得它太轻。",
    },
]

